---
title: "My Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---

## loading data

We're gonna look at NYC Airbnb data.

```{r}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(rvest)
library(httr)
```

```{r}
nyc_restr = 
  GET('https://data.cityofnewyork.us/resource/43nn-pn8j.csv',
      query = list('$limit' = 4000)) %>% 
  content('parse') %>% 
  drop_na(score) %>% 
  drop_na(grade)
```

## Scatterplot

```{r}
nyc_restr %>% 
  mutate(text_label = str_c(dba, '\nScore:', score)) %>% 
  filter(longitude < -70, latitude > 40) %>% 
  plot_ly(
    x = ~latitude, y = ~longitude, color = ~score, text = ~text_label, 
    alpha = .5, 
    type = 'scatter', mode = 'markers', colors = 'viridis')

##the dots clustering in a small area
```


##Boxplot

```{r}
nyc_restr %>% 
  mutate(boro = fct_reorder(boro, score)) %>% 
  plot_ly(y = ~score, x = ~boro, color =~boro,
          type = 'box', colors = 'viridis')
```

##Barplot

```{r}
nyc_restr %>% 
  count(cuisine_description) %>% 
  mutate(cuisine_description = fct_reorder(cuisine_description, n)) %>% 
  plot_ly(x = ~cuisine_description, y =~n,color = ~cuisine_description, type = 'bar', colors = 'viridis')%>% 
  layout(showlegend = FALSE)
```


